/**
 * Staging-only guards, written into dist/ after a staging build.
 *
 * The meta robots tag in BaseLayout is the primary protection, but it only
 * covers HTML. These two files close the remaining gaps:
 *
 *  - .htaccess sends `X-Robots-Tag: noindex, nofollow` on EVERY response from
 *    the folder, including sitemap-0.xml and llms.txt, which a meta tag cannot
 *    reach. Apache (cPanel) applies it to the directory it sits in and below.
 *
 *  - robots.txt is replaced with a blanket disallow. Note this file is NOT
 *    authoritative at /new/robots.txt — crawlers only read the one at the
 *    domain root — so it is defence in depth, not the actual control. The
 *    strongest extra step is one line in the live root robots.txt:
 *        Disallow: /new/
 */
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dist = resolve(root, "dist");
const BASE = (process.env.SITE_BASE || "").replace(/\/+$/, "");

/*
 * Redirects fall into two groups, and only one of them belongs here.
 *
 * The legacy WordPress URLs (/solaredge/, /residential/, …) live at the domain
 * root, so their rules go in the root .htaccess at go-live — see
 * dist/redirects.apache.conf. Putting them under /new would do nothing.
 *
 * In-site renames are different: when a page's own URL changes, the old URL
 * exists inside this build's namespace and must redirect under the base too,
 * or the staging preview 404s on a link that works in production.
 */
const IN_SITE = ["/services/", "/products/", "/brands/", "/locations/", "/resources/"];

const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

let inSiteRules = "";
if (BASE) {
  const raw = JSON.parse(await readFile(resolve(root, "src/data/redirects.json"), "utf8"));
  const rules = Object.entries(raw)
    .filter(([from]) => !from.startsWith("_"))
    .filter(([from]) => IN_SITE.some((p) => from.startsWith(p)));

  if (rules.length) {
    inSiteRules = [
      "",
      "# Renamed pages, rewritten under the staging base.",
      "<IfModule mod_alias.c>",
      ...rules.map(
        ([from, to]) => `  RedirectMatch 301 ^${escapeRe(BASE + from)}$ ${BASE}${to}`
      ),
      "</IfModule>",
    ].join("\n");
  }
}

const htaccess = `# Staging copy — keep it out of search results.
# Generated by scripts/staging-assets.mjs. Do not edit by hand.
<IfModule mod_headers.c>
  Header set X-Robots-Tag "noindex, nofollow, noarchive"
</IfModule>

# Serve pretty URLs from the directory-per-page build.
DirectoryIndex index.html

<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/css application/javascript application/json image/svg+xml text/xml
</IfModule>

# Hashed asset filenames change on every build, so they can be cached hard.
<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresByType text/css "access plus 1 year"
  ExpiresByType application/javascript "access plus 1 year"
  ExpiresByType image/svg+xml "access plus 1 month"
  ExpiresByType text/html "access plus 0 seconds"
</IfModule>
${inSiteRules}
`;

const robots = `# Staging copy of the Advanced Solar Tech website.
# Not for indexing. The live site is at https://advancedsolartec.com.au/
#
# Crawlers read robots.txt from the domain root, not from a subfolder, so this
# file is defence in depth. The real controls are the noindex,nofollow meta tag
# on every page and the X-Robots-Tag header in .htaccess.

User-agent: *
Disallow: /
`;

await Promise.all([
  writeFile(resolve(dist, ".htaccess"), htaccess, "utf8"),
  writeFile(resolve(dist, "robots.txt"), robots, "utf8"),
]);

console.log(
  `[staging] Wrote .htaccess (X-Robots-Tag${inSiteRules ? " + in-site 301s" : ""}) and a disallow-all robots.txt.`
);
